server:
  port: 8061

spring:
  application:
    name: springcloud-consumer-blog


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1314/eureka/ #注册地址
  instance:
    instance-id: springcloud-consumer-blog:8061